export const noteTemplates: Record<string, any> = {
    vitamins: {
      backgroundColor: "#ffffff",
      title: {
        text: "Vitaminas",
        left: 40,
        top: 30,
        fontSize: 48,
        fontFamily: "Pacifico, cursive",
        color: "#333333",
        fontWeight: "bold",
      },
      decorations: [
        {
          type: "line",
          x1: 40,
          y1: 45,
          x2: 300,
          y2: 45,
          color: "#ffcc00",
          strokeWidth: 3,
        },
        {
          type: "line",
          x1: 300,
          y1: 45,
          x2: 760,
          y2: 45,
          color: "#ffcc00",
          strokeWidth: 3,
        },
      ],
      sections: [
        {
          heading: {
            text: "Vitamina A",
            left: 60,
            top: 100,
            fontSize: 24,
            fontFamily: "Montserrat, sans-serif",
            color: "#333333",
            fontWeight: "bold",
            marginBottom: 30,
          },
          bulletPoints: [
            {
              text: "Importante para la visión",
              left: 80,
              fontSize: 16,
              fontFamily: "Shadows Into Light, cursive",
              color: "#333333",
              marginBottom: 20,
            },
            {
              text: "Ayuda al sistema inmunológico",
              left: 80,
              fontSize: 16,
              fontFamily: "Shadows Into Light, cursive",
              color: "#333333",
              marginBottom: 20,
            },
            {
              text: "Se encuentra en zanahorias y batatas",
              left: 80,
              fontSize: 16,
              fontFamily: "Shadows Into Light, cursive",
              color: "#333333",
              marginBottom: 30,
            },
          ],
          divider: {
            x1: 60,
            x2: 380,
            color: "#f0f0f0",
            strokeWidth: 2,
            marginBottom: 20,
          },
        },
        {
          heading: {
            text: "Vitamina B",
            left: 420,
            top: 100,
            fontSize: 24,
            fontFamily: "Montserrat, sans-serif",
            color: "#333333",
            fontWeight: "bold",
            marginBottom: 30,
          },
          bulletPoints: [
            {
              text: "Ayuda a convertir alimentos en energía",
              left: 440,
              fontSize: 16,
              fontFamily: "Shadows Into Light, cursive",
              color: "#333333",
              marginBottom: 20,
            },
            {
              text: "Importante para el sistema nervioso",
              left: 440,
              fontSize: 16,
              fontFamily: "Shadows Into Light, cursive",
              color: "#333333",
              marginBottom: 20,
            },
            {
              text: "Se encuentra en carnes, huevos y legumbres",
              left: 440,
              fontSize: 16,
              fontFamily: "Shadows Into Light, cursive",
              color: "#333333",
              marginBottom: 30,
            },
          ],
          divider: {
            x1: 420,
            x2: 740,
            color: "#f0f0f0",
            strokeWidth: 2,
            marginBottom: 20,
          },
        },
        {
          heading: {
            text: "Vitamina C",
            left: 60,
            top: 250,
            fontSize: 24,
            fontFamily: "Montserrat, sans-serif",
            color: "#333333",
            fontWeight: "bold",
            marginBottom: 30,
          },
          bulletPoints: [
            {
              text: "Antioxidante que protege las células",
              left: 80,
              fontSize: 16,
              fontFamily: "Shadows Into Light, cursive",
              color: "#333333",
              marginBottom: 20,
            },
            {
              text: "Ayuda a la absorción de hierro",
              left: 80,
              fontSize: 16,
              fontFamily: "Shadows Into Light, cursive",
              color: "#333333",
              marginBottom: 20,
            },
            {
              text: "Se encuentra en cítricos y fresas",
              left: 80,
              fontSize: 16,
              fontFamily: "Shadows Into Light, cursive",
              color: "#333333",
              marginBottom: 30,
            },
          ],
          divider: {
            x1: 60,
            x2: 380,
            color: "#f0f0f0",
            strokeWidth: 2,
            marginBottom: 20,
          },
        },
        {
          heading: {
            text: "Vitamina D",
            left: 420,
            top: 250,
            fontSize: 24,
            fontFamily: "Montserrat, sans-serif",
            color: "#333333",
            fontWeight: "bold",
            marginBottom: 30,
          },
          bulletPoints: [
            {
              text: "Importante para huesos y dientes",
              left: 440,
              fontSize: 16,
              fontFamily: "Shadows Into Light, cursive",
              color: "#333333",
              marginBottom: 20,
            },
            {
              text: "Ayuda a absorber calcio",
              left: 440,
              fontSize: 16,
              fontFamily: "Shadows Into Light, cursive",
              color: "#333333",
              marginBottom: 20,
            },
            {
              text: "Se produce con exposición al sol",
              left: 440,
              fontSize: 16,
              fontFamily: "Shadows Into Light, cursive",
              color: "#333333",
              marginBottom: 30,
            },
          ],
          divider: {
            x1: 420,
            x2: 740,
            color: "#f0f0f0",
            strokeWidth: 2,
            marginBottom: 20,
          },
        },
        {
          heading: {
            text: "Vitamina E",
            left: 60,
            top: 400,
            fontSize: 24,
            fontFamily: "Montserrat, sans-serif",
            color: "#333333",
            fontWeight: "bold",
            marginBottom: 30,
          },
          bulletPoints: [
            {
              text: "Antioxidante que protege las células",
              left: 80,
              fontSize: 16,
              fontFamily: "Shadows Into Light, cursive",
              color: "#333333",
              marginBottom: 20,
            },
            {
              text: "Importante para la piel y ojos",
              left: 80,
              fontSize: 16,
              fontFamily: "Shadows Into Light, cursive",
              color: "#333333",
              marginBottom: 20,
            },
            {
              text: "Se encuentra en aceites vegetales y nueces",
              left: 80,
              fontSize: 16,
              fontFamily: "Shadows Into Light, cursive",
              color: "#333333",
              marginBottom: 30,
            },
          ],
          divider: {
            x1: 60,
            x2: 380,
            color: "#f0f0f0",
            strokeWidth: 2,
            marginBottom: 20,
          },
        },
        {
          heading: {
            text: "Vitamina K",
            left: 420,
            top: 400,
            fontSize: 24,
            fontFamily: "Montserrat, sans-serif",
            color: "#333333",
            fontWeight: "bold",
            marginBottom: 30,
          },
          bulletPoints: [
            {
              text: "Esencial para la coagulación de la sangre",
              left: 440,
              fontSize: 16,
              fontFamily: "Shadows Into Light, cursive",
              color: "#333333",
              marginBottom: 20,
            },
            {
              text: "Ayuda a mantener huesos sanos",
              left: 440,
              fontSize: 16,
              fontFamily: "Shadows Into Light, cursive",
              color: "#333333",
              marginBottom: 20,
            },
            {
              text: "Se encuentra en vegetales de hoja verde",
              left: 440,
              fontSize: 16,
              fontFamily: "Shadows Into Light, cursive",
              color: "#333333",
              marginBottom: 30,
            },
          ],
          divider: {
            x1: 420,
            x2: 740,
            color: "#f0f0f0",
            strokeWidth: 2,
            marginBottom: 20,
          },
        },
      ],
    },
  
    idealGas: {
      backgroundColor: "#ffffff",
      title: {
        text: "Ideal Gas",
        left: 40,
        top: 30,
        fontSize: 48,
        fontFamily: "Pacifico, cursive",
        color: "#333333",
        fontWeight: "bold",
      },
      subtitle: {
        text: "Gas • Liquids • Solids",
        left: 50,
        top: 100,
        width: 700,
        fontSize: 18,
        fontFamily: "Montserrat, sans-serif",
        color: "#666666",
        fontStyle: "italic",
      },
      sections: [
        {
          heading: {
            text: "Ideal Gas Law",
            left: 40,
            top: 150,
            fontSize: 28,
            fontFamily: "Montserrat, sans-serif",
            color: "#333333",
            fontWeight: "bold",
            marginBottom: 30,
          },
          content: {
            text: "PV = nRT",
            left: 60,
            fontSize: 24,
            fontFamily: "Courier New, monospace",
            color: "#333333",
            marginBottom: 20,
          },
          bulletPoints: [
            {
              text: "P is pressure (atm)",
              left: 60,
              fontSize: 16,
              fontFamily: "Shadows Into Light, cursive",
              color: "#333333",
              marginBottom: 20,
            },
            {
              text: "V is volume (L)",
              left: 60,
              fontSize: 16,
              fontFamily: "Shadows Into Light, cursive",
              color: "#333333",
              marginBottom: 20,
            },
            {
              text: "n is moles of gas",
              left: 60,
              fontSize: 16,
              fontFamily: "Shadows Into Light, cursive",
              color: "#333333",
              marginBottom: 20,
            },
            {
              text: "R is universal gas constant",
              left: 60,
              fontSize: 16,
              fontFamily: "Shadows Into Light, cursive",
              color: "#333333",
              marginBottom: 20,
            },
            {
              text: "T is temperature (K)",
              left: 60,
              fontSize: 16,
              fontFamily: "Shadows Into Light, cursive",
              color: "#333333",
              marginBottom: 30,
            },
          ],
        },
        {
          heading: {
            text: "Universal Gas Constant",
            left: 40,
            top: 350,
            fontSize: 24,
            fontFamily: "Montserrat, sans-serif",
            color: "#333333",
            fontWeight: "bold",
            marginBottom: 30,
          },
          content: {
            text: "R = 0.08206 L·atm/mol·K",
            left: 60,
            fontSize: 20,
            fontFamily: "Courier New, monospace",
            color: "#333333",
            marginBottom: 30,
          },
        },
        {
          heading: {
            text: "Pressure-Volume Relationship",
            left: 400,
            top: 150,
            fontSize: 24,
            fontFamily: "Montserrat, sans-serif",
            color: "#333333",
            fontWeight: "bold",
            marginBottom: 30,
          },
          formulas: [
            {
              text: "P₁V₁ = P₂V₂",
              left: 420,
              fontSize: 20,
              fontFamily: "Courier New, monospace",
              color: "#333333",
              marginBottom: 20,
              background: {
                left: 410,
                width: 150,
                height: 40,
                fill: "#f5f5f5",
                rx: 4,
                ry: 4,
              },
            },
          ],
          content: {
            text: "At constant temperature and amount of gas, pressure and volume are inversely proportional.",
            left: 420,
            width: 350,
            fontSize: 16,
            fontFamily: "Shadows Into Light, cursive",
            color: "#333333",
            marginBottom: 30,
          },
        },
        {
          heading: {
            text: "Temperature-Volume Relationship",
            left: 400,
            top: 280,
            fontSize: 24,
            fontFamily: "Montserrat, sans-serif",
            color: "#333333",
            fontWeight: "bold",
            marginBottom: 30,
          },
          formulas: [
            {
              text: "V₁/T₁ = V₂/T₂",
              left: 420,
              fontSize: 20,
              fontFamily: "Courier New, monospace",
              color: "#333333",
              marginBottom: 20,
              background: {
                left: 410,
                width: 150,
                height: 40,
                fill: "#f5f5f5",
                rx: 4,
                ry: 4,
              },
            },
          ],
          content: {
            text: "At constant pressure and amount of gas, volume and temperature are directly proportional.",
            left: 420,
            width: 350,
            fontSize: 16,
            fontFamily: "Shadows Into Light, cursive",
            color: "#333333",
            marginBottom: 30,
          },
        },
        {
          heading: {
            text: "Temperature-Pressure Relationship",
            left: 400,
            top: 410,
            fontSize: 24,
            fontFamily: "Montserrat, sans-serif",
            color: "#333333",
            fontWeight: "bold",
            marginBottom: 30,
          },
          formulas: [
            {
              text: "P₁/T₁ = P₂/T₂",
              left: 420,
              fontSize: 20,
              fontFamily: "Courier New, monospace",
              color: "#333333",
              marginBottom: 20,
              background: {
                left: 410,
                width: 150,
                height: 40,
                fill: "#f5f5f5",
                rx: 4,
                ry: 4,
              },
            },
          ],
          content: {
            text: "At constant volume and amount of gas, pressure and temperature are directly proportional.",
            left: 420,
            width: 350,
            fontSize: 16,
            fontFamily: "Shadows Into Light, cursive",
            color: "#333333",
            marginBottom: 30,
          },
        },
      ],
    },
  
    chemistryBasics: {
      backgroundColor: "#f8f8f8",
      title: {
        text: "Chemistry Basics",
        left: 40,
        top: 30,
        fontSize: 48,
        fontFamily: "Pacifico, cursive",
        color: "#333333",
        fontWeight: "bold",
      },
      subtitle: {
        text: "UNIT 1",
        left: 350,
        top: 50,
        fontSize: 18,
        fontFamily: "Montserrat, sans-serif",
        color: "#666666",
        fontWeight: "bold",
      },
      sections: [
        {
          heading: {
            text: "LAB EQUIPMENT",
            left: 40,
            top: 100,
            fontSize: 24,
            fontFamily: "Montserrat, sans-serif",
            color: "#333333",
            fontWeight: "bold",
            marginBottom: 30,
          },
          icons: [
            {
              type: "rect",
              left: 60,
              top: 140,
              width: 40,
              height: 60,
              stroke: "#333333",
              fill: "transparent",
              label: "beaker",
              labelOffsetY: 70,
            },
            {
              type: "rect",
              left: 120,
              top: 140,
              width: 30,
              height: 60,
              stroke: "#333333",
              fill: "transparent",
              label: "erlenmeyer flask",
              labelOffsetY: 70,
            },
            {
              type: "rect",
              left: 180,
              top: 140,
              width: 20,
              height: 60,
              stroke: "#333333",
              fill: "transparent",
              label: "test tube",
              labelOffsetY: 70,
            },
            {
              type: "rect",
              left: 240,
              top: 140,
              width: 20,
              height: 60,
              stroke: "#333333",
              fill: "transparent",
              label: "graduated cylinder",
              labelOffsetY: 70,
            },
            {
              type: "circle",
              left: 300,
              top: 160,
              radius: 20,
              stroke: "#333333",
              fill: "transparent",
              label: "crucible",
              labelOffsetY: 50,
            },
            {
              type: "rect",
              left: 360,
              top: 140,
              width: 60,
              height: 40,
              stroke: "#333333",
              fill: "transparent",
              label: "laboratory burner",
              labelOffsetY: 70,
            },
            {
              type: "rect",
              left: 440,
              top: 140,
              width: 10,
              height: 60,
              stroke: "#333333",
              fill: "transparent",
              label: "thermometer",
              labelOffsetY: 70,
            },
            {
              type: "rect",
              left: 500,
              top: 140,
              width: 40,
              height: 10,
              stroke: "#333333",
              fill: "transparent",
              label: "pipette",
              labelOffsetY: 70,
            },
          ],
        },
        {
          heading: {
            text: "DENSITY",
            left: 40,
            top: 250,
            fontSize: 24,
            fontFamily: "Montserrat, sans-serif",
            color: "#333333",
            fontWeight: "bold",
            marginBottom: 20,
          },
          formulas: [
            {
              text: "density = mass/volume",
              left: 60,
              fontSize: 20,
              fontFamily: "Courier New, monospace",
              color: "#333333",
              marginBottom: 20,
            },
            {
              text: "d = m/V",
              left: 60,
              fontSize: 20,
              fontFamily: "Courier New, monospace",
              color: "#333333",
              marginBottom: 20,
            },
          ],
          content: {
            text: "Units: g/mL, g/cm³",
            left: 60,
            fontSize: 16,
            fontFamily: "Shadows Into Light, cursive",
            color: "#333333",
            marginBottom: 20,
          },
        },
        {
          heading: {
            text: "PARTICLE DIAGRAMS",
            left: 400,
            top: 250,
            fontSize: 24,
            fontFamily: "Montserrat, sans-serif",
            color: "#333333",
            fontWeight: "bold",
            marginBottom: 20,
          },
          grid: {
            left: 420,
            size: 20,
            width: 200,
            height: 100,
            background: "#ffffff",
            stroke: "#cccccc",
            lineColor: "#dddddd",
            marginBottom: 30,
          },
          content: {
            text: "most dense ——→ least dense",
            left: 420,
            fontSize: 16,
            fontFamily: "Shadows Into Light, cursive",
            color: "#333333",
            marginBottom: 30,
          },
        },
        {
          heading: {
            text: "SIGNIFICANT FIGURES",
            left: 40,
            top: 400,
            fontSize: 24,
            fontFamily: "Montserrat, sans-serif",
            color: "#333333",
            fontWeight: "bold",
            marginBottom: 20,
          },
          content: {
            text: "Rules:",
            left: 60,
            fontSize: 18,
            fontFamily: "Shadows Into Light, cursive",
            fontWeight: "bold",
            color: "#333333",
            marginBottom: 20,
          },
          bulletPoints: [
            {
              text: "1. Non-zero digits are always significant",
              left: 60,
              fontSize: 16,
              fontFamily: "Shadows Into Light, cursive",
              color: "#333333",
              marginBottom: 15,
            },
            {
              text: "2. Zeros between non-zero digits are significant",
              left: 60,
              fontSize: 16,
              fontFamily: "Shadows Into Light, cursive",
              color: "#333333",
              marginBottom: 15,
            },
            {
              text: "3. Trailing zeros after decimal point are significant",
              left: 60,
              fontSize: 16,
              fontFamily: "Shadows Into Light, cursive",
              color: "#333333",
              marginBottom: 15,
            },
            {
              text: "4. Leading zeros are never significant",
              left: 60,
              fontSize: 16,
              fontFamily: "Shadows Into Light, cursive",
              color: "#333333",
              marginBottom: 15,
            },
          ],
        },
        {
          heading: {
            text: "SCIENTIFIC NOTATION",
            left: 40,
            top: 550,
            fontSize: 24,
            fontFamily: "Montserrat, sans-serif",
            color: "#333333",
            fontWeight: "bold",
            marginBottom: 20,
          },
          bulletPoints: [
            {
              text: "• Move decimal so only one digit is to the left",
              left: 60,
              fontSize: 16,
              fontFamily: "Shadows Into Light, cursive",
              color: "#333333",
              marginBottom: 15,
            },
            {
              text: "• Negative exponent = move decimal left",
              left: 60,
              fontSize: 16,
              fontFamily: "Shadows Into Light, cursive",
              color: "#333333",
              marginBottom: 15,
            },
            {
              text: "• Positive exponent = move decimal right",
              left: 60,
              fontSize: 16,
              fontFamily: "Shadows Into Light, cursive",
              color: "#333333",
              marginBottom: 15,
            },
          ],
        },
        {
          heading: {
            text: "PERCENT ERROR",
            left: 400,
            top: 550,
            fontSize: 24,
            fontFamily: "Montserrat, sans-serif",
            color: "#333333",
            fontWeight: "bold",
            marginBottom: 20,
          },
          formulas: [
            {
              text: "% error = |accepted value - experimental| / accepted value × 100%",
              left: 420,
              fontSize: 16,
              fontFamily: "Courier New, monospace",
              color: "#333333",
              marginBottom: 20,
              background: {
                left: 410,
                width: 350,
                height: 40,
                fill: "#f5f5f5",
                rx: 4,
                ry: 4,
              },
            },
          ],
          content: {
            text: "• Always include units in answers!",
            left: 420,
            fontSize: 16,
            fontFamily: "Shadows Into Light, cursive",
            color: "#333333",
            marginBottom: 30,
          },
        },
      ],
    },
  
    metacognition: {
      backgroundColor: "#ffffff",
      title: {
        text: "Metacognition",
        left: 40,
        top: 30,
        fontSize: 48,
        fontFamily: "Pacifico, cursive",
        color: "#333333",
        fontWeight: "bold",
      },
      decorations: [
        {
          type: "line",
          x1: 40,
          y1: 85,
          x2: 760,
          y2: 85,
          color: "#90caf9",
          strokeWidth: 3,
        },
        {
          type: "line",
          x1: 40,
          y1: 90,
          x2: 760,
          y2: 90,
          color: "#90caf9",
          strokeWidth: 1,
        },
      ],
      sections: [
        {
          heading: {
            text: "Before Reading",
            left: 60,
            top: 120,
            fontSize: 24,
            fontFamily: "Montserrat, sans-serif",
            color: "#1976d2",
            fontWeight: "bold",
            marginBottom: 30,
          },
          bulletPoints: [
            {
              text: "• Skim through headings",
              left: 80,
              fontSize: 16,
              fontFamily: "Shadows Into Light, cursive",
              color: "#333333",
              marginBottom: 15,
            },
            {
              text: "• Identify important details",
              left: 80,
              fontSize: 16,
              fontFamily: "Shadows Into Light, cursive",
              color: "#333333",
              marginBottom: 15,
            },
            {
              text: "• Set reading goals",
              left: 80,
              fontSize: 16,
              fontFamily: "Shadows Into Light, cursive",
              color: "#333333",
              marginBottom: 15,
            },
            {
              text: "• Activate prior knowledge",
              left: 80,
              fontSize: 16,
              fontFamily: "Shadows Into Light, cursive",
              color: "#333333",
              marginBottom: 15,
            },
            {
              text: "• Predict content",
              left: 80,
              fontSize: 16,
              fontFamily: "Shadows Into Light, cursive",
              color: "#333333",
              marginBottom: 15,
            },
          ],
        },
        {
          heading: {
            text: "During Reading",
            left: 60,
            top: 280,
            fontSize: 24,
            fontFamily: "Montserrat, sans-serif",
            color: "#1976d2",
            fontWeight: "bold",
            marginBottom: 30,
          },
          bulletPoints: [
            {
              text: "• Extract information",
              left: 80,
              fontSize: 16,
              fontFamily: "Shadows Into Light, cursive",
              color: "#333333",
              marginBottom: 15,
            },
            {
              text: "• Look for topic-specific information you're looking for",
              left: 80,
              fontSize: 16,
              fontFamily: "Shadows Into Light, cursive",
              color: "#333333",
              marginBottom: 15,
            },
            {
              text: "• Annotate text and mark key ideas",
              left: 80,
              fontSize: 16,
              fontFamily: "Shadows Into Light, cursive",
              color: "#333333",
              marginBottom: 15,
            },
            {
              text: "• Selectively read and skip through pages",
              left: 80,
              fontSize: 16,
              fontFamily: "Shadows Into Light, cursive",
              color: "#333333",
              marginBottom: 15,
            },
          ],
        },
        {
          heading: {
            text: "Reading Strategies",
            left: 60,
            top: 400,
            fontSize: 24,
            fontFamily: "Montserrat, sans-serif",
            color: "#1976d2",
            fontWeight: "bold",
            marginBottom: 30,
          },
          bulletPoints: [
            {
              text: "• Analyze structure of text",
              left: 80,
              fontSize: 16,
              fontFamily: "Shadows Into Light, cursive",
              color: "#333333",
              marginBottom: 15,
            },
            {
              text: "• Use headings using scanning, color coding, and its presence in text",
              left: 80,
              fontSize: 16,
              fontFamily: "Shadows Into Light, cursive",
              color: "#333333",
              marginBottom: 15,
            },
            {
              text: "• Identify various points",
              left: 80,
              fontSize: 16,
              fontFamily: "Shadows Into Light, cursive",
              color: "#333333",
              marginBottom: 15,
            },
            {
              text: "• Recurring words",
              left: 80,
              fontSize: 16,
              fontFamily: "Shadows Into Light, cursive",
              color: "#333333",
              marginBottom: 15,
            },
          ],
        },
        {
          heading: {
            text: "After Reading",
            left: 60,
            top: 520,
            fontSize: 24,
            fontFamily: "Montserrat, sans-serif",
            color: "#1976d2",
            fontWeight: "bold",
            marginBottom: 30,
          },
          bulletPoints: [
            {
              text: "• Ask critical thinking questions about content of paragraph",
              left: 80,
              fontSize: 16,
              fontFamily: "Shadows Into Light, cursive",
              color: "#333333",
              marginBottom: 15,
            },
            {
              text: "• Must be written in a single sentence and should only contain one author's most important point",
              left: 80,
              fontSize: 16,
              fontFamily: "Shadows Into Light, cursive",
              color: "#333333",
              marginBottom: 15,
            },
            {
              text: "• Evaluate mental processes",
              left: 80,
              fontSize: 16,
              fontFamily: "Shadows Into Light, cursive",
              color: "#333333",
              marginBottom: 15,
            },
            {
              text: "• Reflect on reading strategies, strengths, weaknesses, etc.",
              left: 80,
              fontSize: 16,
              fontFamily: "Shadows Into Light, cursive",
              color: "#333333",
              marginBottom: 15,
            },
            {
              text: "• Mark, come back, review, during, after reading",
              left: 80,
              fontSize: 16,
              fontFamily: "Shadows Into Light, cursive",
              color: "#333333",
              marginBottom: 15,
            },
            {
              text: "• Creating",
              left: 80,
              fontSize: 16,
              fontFamily: "Shadows Into Light, cursive",
              color: "#333333",
              marginBottom: 15,
            },
          ],
        },
      ],
    },
  
    chemistryFormulas: {
      backgroundColor: "#ffffff",
      title: {
        text: "Chemistry",
        left: 40,
        top: 30,
        fontSize: 48,
        fontFamily: "Pacifico, cursive",
        color: "#333333",
        fontWeight: "bold",
      },
      subtitle: {
        text: "UNIT 1 (Properties & Matter)",
        left: 50,
        top: 100,
        width: 700,
        fontSize: 18,
        fontFamily: "Montserrat, sans-serif",
        color: "#666666",
        fontStyle: "italic",
      },
      sections: [
        {
          heading: {
            text: "MATTER",
            left: 40,
            top: 150,
            fontSize: 24,
            fontFamily: "Montserrat, sans-serif",
            color: "#333333",
            fontWeight: "bold",
            marginBottom: 20,
          },
          bulletPoints: [
            {
              text: "• Anything that has mass and occupies space",
              left: 60,
              fontSize: 16,
              fontFamily: "Shadows Into Light, cursive",
              color: "#333333",
              marginBottom: 15,
            },
            {
              text: "• Composed of atoms",
              left: 60,
              fontSize: 16,
              fontFamily: "Shadows Into Light, cursive",
              color: "#333333",
              marginBottom: 15,
            },
            {
              text: "• Exists in different states: solid, liquid, gas",
              left: 60,
              fontSize: 16,
              fontFamily: "Shadows Into Light, cursive",
              color: "#333333",
              marginBottom: 15,
            },
          ],
        },
        {
          heading: {
            text: "PHYSICAL PROPERTIES",
            left: 400,
            top: 150,
            fontSize: 24,
            fontFamily: "Montserrat, sans-serif",
            color: "#333333",
            fontWeight: "bold",
            marginBottom: 20,
          },
          bulletPoints: [
            {
              text: "• Properties that can be observed without changing the identity of the substance",
              left: 420,
              fontSize: 16,
              fontFamily: "Shadows Into Light, cursive",
              color: "#333333",
              marginBottom: 15,
            },
            {
              text: "• Examples: color, odor, density, melting point, boiling point",
              left: 420,
              fontSize: 16,
              fontFamily: "Shadows Into Light, cursive",
              color: "#333333",
              marginBottom: 15,
            },
          ],
        },
        {
          heading: {
            text: "DENSITY",
            left: 40,
            top: 280,
            fontSize: 24,
            fontFamily: "Montserrat, sans-serif",
            color: "#333333",
            fontWeight: "bold",
            marginBottom: 20,
          },
          formulas: [
            {
              text: "Density = mass/volume",
              left: 60,
              fontSize: 20,
              fontFamily: "Courier New, monospace",
              color: "#333333",
              marginBottom: 20,
              background: {
                left: 50,
                width: 250,
                height: 40,
                fill: "#f5f5f5",
                rx: 4,
                ry: 4,
              },
            },
            {
              text: "d = m/V",
              left: 60,
              fontSize: 20,
              fontFamily: "Courier New, monospace",
              color: "#333333",
              marginBottom: 20,
            },
          ],
          bulletPoints: [
            {
              text: "• Units: g/mL, g/cm³",
              left: 60,
              fontSize: 16,
              fontFamily: "Shadows Into Light, cursive",
              color: "#333333",
              marginBottom: 15,
            },
            {
              text: "• Intensive property (doesn't depend on amount)",
              left: 60,
              fontSize: 16,
              fontFamily: "Shadows Into Light, cursive",
              color: "#333333",
              marginBottom: 15,
            },
          ],
        },
        {
          heading: {
            text: "FORMULAS",
            left: 400,
            top: 280,
            fontSize: 24,
            fontFamily: "Montserrat, sans-serif",
            color: "#333333",
            fontWeight: "bold",
            marginBottom: 20,
          },
          formulas: [
            {
              text: "ΔT = Tfinal - Tinitial",
              left: 420,
              fontSize: 20,
              fontFamily: "Courier New, monospace",
              color: "#333333",
              marginBottom: 20,
              background: {
                left: 410,
                width: 250,
                height: 40,
                fill: "#f5f5f5",
                rx: 4,
                ry: 4,
              },
            },
            {
              text: "Q = mcΔT",
              left: 420,
              fontSize: 20,
              fontFamily: "Courier New, monospace",
              color: "#333333",
              marginBottom: 20,
              background: {
                left: 410,
                width: 150,
                height: 40,
                fill: "#f5f5f5",
                rx: 4,
                ry: 4,
              },
            },
            {
              text: "E = hv",
              left: 420,
              fontSize: 20,
              fontFamily: "Courier New, monospace",
              color: "#333333",
              marginBottom: 20,
              background: {
                left: 410,
                width: 150,
                height: 40,
                fill: "#f5f5f5",
                rx: 4,
                ry: 4,
              },
            },
          ],
        },
        {
          heading: {
            text: "THERMOCHEMISTRY",
            left: 40,
            top: 450,
            fontSize: 24,
            fontFamily: "Montserrat, sans-serif",
            color: "#333333",
            fontWeight: "bold",
            marginBottom: 20,
          },
          bulletPoints: [
            {
              text: "• Exothermic: releases heat (negative ΔH)",
              left: 60,
              fontSize: 16,
              fontFamily: "Shadows Into Light, cursive",
              color: "#333333",
              marginBottom: 15,
            },
            {
              text: "• Endothermic: absorbs heat (positive ΔH)",
              left: 60,
              fontSize: 16,
              fontFamily: "Shadows Into Light, cursive",
              color: "#333333",
              marginBottom: 15,
            },
            {
              text: "• Heat capacity: amount of heat needed to raise temperature by 1°C",
              left: 60,
              fontSize: 16,
              fontFamily: "Shadows Into Light, cursive",
              color: "#333333",
              marginBottom: 15,
            },
          ],
        },
        {
          heading: {
            text: "UNIT CONVERSIONS",
            left: 400,
            top: 450,
            fontSize: 24,
            fontFamily: "Montserrat, sans-serif",
            color: "#333333",
            fontWeight: "bold",
            marginBottom: 20,
          },
          content: {
            text: "1000 mL = 1 L\n1 L = 1000 cm³\n1000 g = 1 kg",
            left: 420,
            fontSize: 16,
            fontFamily: "Courier New, monospace",
            color: "#333333",
            marginBottom: 20,
          },
          grid: {
            left: 420,
            size: 20,
            width: 300,
            height: 60,
            background: "#ffffff",
            stroke: "#cccccc",
            lineColor: "#dddddd",
            marginBottom: 30,
          },
        },
      ],
    },
  }
  